### PR TITLE
promo code endpoint closes #82

### LINKED ISSUE #82: Create promo code endpoint (2)

### PR DESCRIPTION
**Pull request by ChuckPierce**
So I created the promo code endpoint with model and model tests.  There was a method that I don't think that I need since I'm using the enumerator.  Also not sure if I need the static method to set the date but would be nice to not have to worry about setting the date on the frontend.  Let me know what you guys think!

### CODE REVIEW

**Comment by ChuckPierce** [comment]
Just added admin auth quickly on the index.js of the endpoint.  However I also was wondering would we want to see past promotions?  In that case I would just change the promotionType to reflect open and closed promotions.  Also, I was just wondering on how we should tackle when promotions expire.  Not sure how to tackle that and thoughts would be appreciated

**Comment by meliis** [comment]
yeah seeing past promotions would probably be a thing.
expiration...can't we just set an expiration date and do some sort of if statement somewhere to check if that date is in the past?

**Comment by meliis** [comment]
i'm good with all this by the way.  nice tests!!

**Comment by ChuckPierce** [comment]
sweet I'll change the type and then merge.  Also I'm going to make the expiration thing an issue.

**Pull request merged**
