### PR TITLE
closes #62

### LINKED ISSUE #62: Write tests for order model and modify per requirements (2)

### PR DESCRIPTION
**Pull request by ChuckPierce**
Here are the model edits and test for the model per the data validation requirements.  Please let me know what you think.  Also, it said in the requirements that we need to refer to a product ID in the lineItem schema.  However, I don't know if that is a good thing because what if the product gets deleted?  I don't know.  Let me know what you guys think

### CODE REVIEW

**Comment by meliis** [comment]
so the thing is, it's true that you don't want any edits to products to affect complete orders.  however, what katie was saying just now is that you DO want them to affect INCOMPLETE orders

**Comment by meliis** [comment]
so how can we reconcile that?

**Comment by ChuckPierce** [comment]
well you can just have it be the product name I guess.  Just in the data validation on learndot it says that it needs a product ID so I didn't know how we would got about doing that.

Also, for the userID the data validations on learn dot say that the orders have to belong to either a user or  session.  So I mean we can make it so userID is not required but I don't know if that goes along with the validations.

**Comment by meliis** [comment]
okay so i drew a masterpiece on the glass pane and we kind of figured it out.  tl;dr you were right

-there is going to be a cart schema + cart collection in database
-your cart id is stored in local storage (for unauthenticated users)
-if someone visits the site and doesn't have an id in local storage, an empty cart is created
-carts of authenticated users have userIds attached to them, carts of unauthenticated users do not
-if an unauthenticated user adds stuff to their cart then logs in, that stuff is added to their actual cart and their "temporary" cart is deleted
-when the user checks out the stuff in the cart becomes an order and the cart disappears from the cart collection in the database
-hooray
-thoughts?

**Comment by ChuckPierce** [comment]
That's fine with me.

**Pull request merged**
